site_name: THETA V Plugin Development Community Guide
site_url: http://theta360.guide/plugin-guide/
site_description: RICOH THETA development for plug-ins and 360 applications include AR and VR applications
site_author: Craig Oda and Jesse Casman
google_analytics: ['UA-73311422-1', 'auto']
theme_dir: theme/material
theme: 
  name: material
  palette:
    primary: 'light green'
    accent: 'lime'
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png

extra:
  social:
    - type: 'github'
      link: 'https://github.com/theta360developers'
    - type: 'twitter'
      link: 'https://twitter.com/theta360dev'
    - type: 'facebook'
      link: 'https://www.facebook.com/theta360guide/'
  
pages: 
  - Overview: index.md
  - Requirements: requirements.md
  - Setup: setup.md
  - Plugin Use: use.md
  - Custom Development: custom.md
  - Workflow Tips: workflow.md
  - Fun Tests: fun.md
  - Concept Ideas: concept.md
  - Community: community.md
  - About: about.md
